apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: ibm-common-services
spec:
  targetNamespaces:
  - ibm-common-services
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: operand-deployment-lifecycle-manager
  namespace: ibm-common-services
spec:
  channel: stable-v1
  name: operand-deployment-lifecycle-manager-app
  source: opencloud-operators
  sourceNamespace: openshift-marketplace
